
// Define translations.
module.config(['$translateProvider', function ($translateProvider) {
    $translateProvider.translations('en', {
        Play: 'Play',
        Pause : 'Pause',
        Reset: 'Reset',
        Edit: 'Edit',
        Close: 'Close',
        Save: 'Save',
        Minutes: 'Minutes',
        Seconds: 'Seconds',
        Place: 'Place',
        Officer: 'Officer',
        Airline: 'Airline',
        Flight: 'Flight',
        'Skipped person': 'Skipped person',
        'Skipped fingerprints': 'Skipped fingerprints',
        'Other errors': 'Other errors',
        'Wrong airline': 'Wrong airline',
        'Machine readable': 'Machine readable',
        'Send and Continue': 'Send & Continue',
        Settings: 'Settings',
        Language: 'Language',
        Survey: 'Survey',
        Records: 'Records',
        Help: 'Help',
        Yes: 'Yes',
        No: 'No',
        Menu: 'Menu',
        Login: 'Login',
        Logout: 'Logout',
        Username: 'Username',
        Password: 'Password',
        Submit: 'Submit',
        'Start date': 'Start date',
        'End date': 'End date',
        Search: 'Search',
        'No data available': 'No data available',
        Delete: 'Delete',
        
		//ktraore()
		
		Device_Categorie : 'Device categorie',
		Location: 'Location',
		Zone: 'Zone',
		Position: 'Position',
		DateTime: 'Date',
		DeviceMovement: 'Device Mouvement',
		Desktop: 'Unité centrale',
		Screen: 'Ecran',
		Suw: 'Windows up',
		Sus: 'System up',
		Cam: 'Caméra',
		Fp: 'Lecteur d"emprunt',
		Pp: 'Lecteur de document',
		Kbd: 'Clavier',
		Mos: 'Souris',
		Ups: 'Onduleur',
		Rcg: '',
		Av: 'Anti-virus',
		Cln: 'Clean',
		Ss: '',
		Snd: 'Son',
		Net: 'Connection internet',
		Swi: '',
		Usb: 'Usb',		
		Time: 'Time',
		IsUsed : 'En Stock',
		//
        formatDate: "MM/DD/YYYY",
        
        msgLoading: 'Loading, please wait...',
        msgEnrollmentSubmitted: 'Enrollment successfully submitted',
        msgAreYouSureYouWantToClearTheChronometer: 'Are you sure that you want to clear the chronometer?',
        msgAreYouSureYouWantToDeleteEnrollment: "Are you sure you want to delete this entry? (this action can't be undo)",
        msgYouAreCurrentlyLoggedAs: "You are currently logged as",
        msgYouMustBeLogged: "You must be logged to perform this action",
        errorAccessDenied: "You don't have enough privileges to access to this functionality",
        errorRequiredField: 'This field is required',
        errorTimeCantBeZero: "The time can't be zero",
        errorInvalidForm: "They are errors in the form",
        errorNetworking: 'The application could not connect with the server. Please verify you network connection or contact your network administrator.',
        errorUnexpectedAtServer: 'An unexpected error ocurred at the server. Please contact your system administrator.',
        errorEmptyUsernameOrPassword: "The username and the password can't be empty",
        errorInvalidLogin: "You could not be logged, the username and/or the password are incorrect"
    });
     
    $translateProvider.translations('es', {
        Play: 'Reproducir',
        Pause : 'Pausar',
        Reset: 'Borrar',
        Edit: 'Editar',
        Close: 'Cerrar',
        Save: 'Guardar',
        Minutes: 'Minutos',
        Seconds: 'Segundos',
        Place: 'Lugar',
        Officer: 'Oficial',
        Airline: 'Aerolínea',
        Flight: 'Vuelo',
        'Skipped person': 'Persona ignorada',
        'Skipped fingerprints': 'Huellas ignoradas',
        'Other errors': 'Otros errores',
        'Wrong airline': 'Aerolínea incorrecta',
        'Machine readable': 'Scaneable',
        'Send and Continue': 'Enviar & Continuar',
        Settings: 'Configuración',
        Language: 'Idioma',
        Survey: 'Formulario',
        Records: 'Historial',
        Help: 'Ayuda',
        Yes: 'Si',
        No: 'No',
        Menu: 'Menú',
        Login: 'Loguearse',
        Logout: 'Desloguearse',
        Username: 'Nombre de usuario',
        Password: 'Contraseña',
        Submit: 'Enviar',
        'Start date': 'Fecha de inicio',
        'End date': 'Fecha de fin',
        Search: 'Buscar',
        'No data available': 'No hay datos disponibles',
        Delete: 'Borrar',
       
	   	//ktraore()
		
		Location: 'localización',
		Zone: 'Zona',
		Position: 'Posición',
		DateTime: 'Fécha',
		DeviceMovement: 'Device Mouvement',
		Desktop: 'Unité centrale',
		Screen: 'Ecran',
		Suw: '',
		Sus: '',
		Cam: 'Caméra',
		Fp: 'Lecteur d"emprunt',
		Pp: 'Lecteur de document',
		Kbd: 'Clavier',
		Mos: 'Souris',
		Ups: 'Onduleur',
		Rcg: '',
		Av: 'Anti-virus',
		Cln: '',
		Ss: '',
		Snd: 'Son',
		Net: 'Connection internet',
		Swi: '',
		Usb: 'Usb',	
		Time: 'Tipo',
		IsUsed : 'En Stock',
		//
	   
        formatDate: "DD/MM/YYYY",
        
        msgLoading: 'Cargando, por favor espere...',
        msgEnrollmentSubmitted: 'Enrolamiento enviado con éxito',
        msgAreYouSureYouWantToClearTheChronometer: '¿Está seguro que desea reiniciar el cronómetro?',
        msgAreYouSureYouWantToDeleteEnrollment: "¿Está seguro que desea borrar este enrolamiento? (esta acción no se puede deshacer)",
        msgYouAreCurrentlyLoggedAs: "Usted se encuentra logueado como",
        msgYouMustBeLogged: "Debe estar logueado para poder realizar esta acción",
        errorAccessDenied: "No tiene los privilegios necesarios para acceder a esta funcionalidad",
        errorRequiredField: 'Este campo es obligatorio',
        errorTimeCantBeZero: 'El tiempo no puede ser cero',
        errorInvalidForm: "El formulario posee errores",
        errorNetworking: 'La aplicación no se pudo conectar con el servidor. Por favor, verifique su conneción a la red o contacte con su administrador de redes.',
        errorUnexpectedAtServer: 'Un error inesperado ocurrió en el servidor. Por favor contacte con su administrador de sistemas.',
        errorEmptyUsernameOrPassword: "El nombre de usuario y la contraseña no pueden ser nulas",
        errorInvalidLogin: "No se pudo realizar el login, el nombre de usuario y/0 la contraseña son incorrectas"
    });
     
    $translateProvider.translations('fr', {
        Play: 'Reproduire',
        Pause : 'Pauser',
        Reset: 'Vider',
        Edit: 'Editer',
        Close: 'Fermer',
        Save: 'Sauver',
        Minutes: 'Minutes',
        Seconds: 'Secondes',
        Place: 'Lieu',
        Officer: 'Officier',
        Airline: 'Compagnie',
        Flight: 'Vol',
        'Skipped person': 'Personne ignoré',
        'Skipped fingerprints': 'Empreintes sautées',
        'Other errors': 'Autres erreurs',
        'Wrong airline': 'Ligne incorrecte',
        'Machine readable': 'Lisible par machine',
        'Send and Continue': 'Envoyer & Continuer',
        Settings: 'Paramètres',
        Language: 'Langue',
        Survey: 'Formulaire',
        Records: 'Historique',
        Help: 'Aide',
        Yes: 'Oui',
        No: 'Non',
        Menu: 'Menu',
        Login: "S'identifier",
        Logout: 'Déconnexion',
        Username: "Nom d'utilisateur",
        Password: 'Mot de passe',
        Submit: 'Envoyer',
        'Start date': 'Date de début',
        'End date': 'Date de fin',
        Search: 'Rechercher',
        'No data available': 'Pas de données disponibles',
        Delete: 'Effacer',
        
		//ktraore()
		
		Device_Categorie : 'Catégorie',
		Location: 'Position',
		Zone: 'Zone',
		Position: 'Emplacement',
		DateTime: 'Date',	
		DeviceMovement: "Mouvement d'équipement",	
		Desktop: 'Unité centrale',
		Screen: 'Ecran',
		Suw: 'Démarrage Windows',
		Sus: 'Démarrage IICS',
		Cam: 'Caméra',
		Fp: 'Lecteur d"emprunt',
		Pp: 'Lecteur de document',
		Kbd: 'Clavier',
		Mos: 'Souris',
		Ups: 'Onduleur',
		Rcg: 'Config Regionale',
		Av: 'Anti-virus',
		Cln: 'Nettoyer',
		Ss: 'Seal securiport',
		Snd: 'Son',
		Net: 'Internet',
		Swi: 'Application installée',
		Usb: 'Usb',
		Time: 'Temps',
		IsUsed: 'En Stock',
		//
		
        formatDate: "DD/MM/YYYY",
        
        msgLoading: 'Veuillez patienter...',
        msgEnrollmentSubmitted: 'Enrôlement envoyé avec succès',
        msgAreYouSureYouWantToClearTheChronometer: 'Etes-vous sûr que vous voulez effacer le chronomètre?',
        msgAreYouSureYouWantToDeleteEnrollment: "Etes-vous sûr que vous voulez effacer l'enrôrelement? (cet action est irreversible)",
        msgYouAreCurrentlyLoggedAs: "Vous avez vous identifié sur le nom d'utilisateur",
        msgYouMustBeLogged: "Vous devez être connecté pour effectuer cette action",
        errorAccessDenied: "Vous ne avez pas assez de privilèges pour accéder à cette fonctionnalité",
        errorRequiredField: 'Ce champ est obligatorie',
        errorTimeCantBeZero: 'Le temps ne peut pas être zero',
        errorInvalidForm: "Le formulaire a des erreurs",
        errorNetworking: "L'application n'a pas pu se connecter au serveur. Veuillez vérifier la connexion réseau ou contactez votre administrateur de réseau.",
        errorUnexpectedAtServer: "Une erreur inattendue s'est produite sur le serveur. Veuillez contacter votre administrateur de systèmes.",
        errorEmptyUsernameOrPassword: "Le nom d'utilisateur et la mot de passe ne peuvent pas être vides",
        errorInvalidLogin: "On n'a pas pu vous identifier, le nom d'utilisateur et/ou la mot de passe sont incorrectes"
    });
     
    var preferred = amplify.store('language');
    if(preferred !== 'en' && preferred !== 'fr' && preferred !== 'es') {
        preferred = 'fr';
        amplify.store('language', preferred);
    }
    $translateProvider.preferredLanguage(preferred);
}]);
